<?php
/**
 * @var Magento\Framework\View\TemplateEngine\Php $this
 * @var Vmasciotta\PrivacyPolicy\Block\PrivacyPolicy $block
 */
if ($block->isPrivacyPolicyEnabled()) : ?>
    <div class="privacy-box">
        <input type="checkbox" id="<?php echo $block->getNameInLayout() ?>" name="<?php echo $block->getNameInLayout() ?>" data-validate="{required:true}" value="Privacy" />
        <label for="<?php echo $block->getNameInLayout() ?>"><span><?php echo __('Ho preso visione e accetto l\'informativa sulla Privacy') ?></span></label>
        <a href="<?php echo $block->getPrivacyUrl() ?>"><?php echo __('Informativa') ?></a>
    </div>
<?php endif; ?>